title: XO Engineering
email: truck@xo.engineering
description: A design company with big plans for little trucks
url: "https://xo.engineering"
github_username:  xoengineering
instagram_username: xoengineering
youtube_username: "@xoengineering"

# Build settings
theme: minima
plugins:
  - jekyll-feed
